services:
  nginx:
    image: nginx:1.28.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro
      - C:/videos/hls:/app/videos/hls:ro
      - C:/images:/app/images:ro
    networks:
      - nginx-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: spring_ols
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.0
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
      
volumes:
  postgres-data: {}
  redis-data:

networks:
  nginx-network:
    driver: bridge